### ISSUE TITLE
keybind detection problem

### ISSUE THREAD

**Issue by ehsansabet** [khodekhadem/magic-mouse#1]
روی ماوس بی سیم شیائومی مدل Silent Edition کار نمی‌کنه متاسفانه

**Comment by khodekhadem** [comment]
کی بایند ها برای موس های مختلف میتونه عدد کلید متفاوتی داشته باشه بخش هایی از کد که Button.button8True یا Button.button8False هست عدد ۸ یا ۹ رو به عدد های دیگه تغییر بدید میتونید کامنت های پرینت ها رو هم بردارید تا خودتون بتونید دیباگ کنید و کد باتن ها رو پیدا کنید
